FORMAT: 1A
HOST: https://apprenticeship-scorecard-api.herokuapp.com/

# Apprenticeship Scorecard

API to access data on UK apprenticeships and providers

## Apprenticeships Collection [/apprenticeships]

List all (by default) apprenticeships in the data set. The results will be paged. The page size and page number can be set by the relevant optional parameters and the total number of results that are selected can be limited by the optional `max_results` parameter.

### List and filter apprenticeships [GET /apprenticeships?q=query-string&max_results=500&page_size=20&page_number=2]

All parameters are optional.

+ Parameters
    + query: learner_stats.total > 200 (string, optional) - a query expression that will be used to filter the list of apprenticeships
    + max_results: 500 (number, optional) - limit the number of apprenticeships that are selected
    + page_size: 20 (number, optional) - limit the number of apprenticeships that are returned in a page
        + Default: 50
    + page_number: 7 (number, optional) - the page number to return
        + Default: 1

+ Response 200 (application/json)

        {
            "results": [
                {
                    "subject_tier_2_code": 0,
                    "subject_tier_2_title": "All",
                    "learner_stats": {
                        "satisfaction": 9.1,
                        "national_satisfaction": 8.6,
                        "age_under_19": 10,
                        "age_19_to_24": 40,
                        "age_25_plus": 110,
                        "total": 160
                    },
                    "description": "All",
                    "provider_id": 10000020,
                    "stats": {
                        "success_rate": 84.2
                    },
                    "national_stats": {
                        "success_rate": 68.9
                    },
                    "earnings": {},
                    "national_earnings": {},
                    "average_cost": 0
                },
                {
                    "subject_tier_2_code": 15.1,
                    "subject_tier_2_title": "Accounting and Finance",
                    "learner_stats": {},
                    "description": "Accounting and Finance",
                    "provider_id": 10000060,
                    "stats": {
                        "success_rate": 90.3
                    },
                    "national_stats": {
                        "success_rate": 76.1
                    },
                    "earnings": {
                        "median": 18700,
                        "proportion_above_21k": 0.33
                    },
                    "national_earnings": {
                        "median": 19100,
                        "proportion_above_21k": 0.34
                    },
                    "average_cost": 0
                }
            ],
            "result_count": 2,
            "page_number": 1,
            "page_size": 50
        }

### List, filter and extract fields from apprenticeships [POST /apprenticeships]

The POST endpoint supports the same parameters as the GET endpoint, but enclosed in a json object rather than being query parameters. In addition, it supports a `fields` parameter that lets you select which fields of the selected objects should be returned in the results. This is a json array of strings, each of which is a path into the json (e.g. `earnings` or `national_earnings.median`. If, for a specific object in the result set, a given path is empty or missing then it will be excluded from the result object. If a result object is empty, because none of the paths match, then it will be excluded from the result set.

Duplicates are removed from the result set. So if, for example, you specify `"fields" : [ "subject_tier_2_code" ]` then you would see only one result object for each unique value of `subject_tier_2_code`.

+ Request (application/json)

        {
            "fields": [
                "earnings",
                "national_earnings"
            ],
            "max_results": 500,
            "page_number": 2,
            "page_size": 10,
            "query": "earnings.median > 0"
        }

        All fields in the request body are optional, but at the very least you must provide an empty json object (`{}`).


+ Response 200 (application/json)

    + Body

            {
                "results": [
                    {
                        "subject_tier_2_code": 0,
                        "subject_tier_2_title": "All",
                        "learner_stats": {
                            "satisfaction": 9.1,
                            "national_satisfaction": 8.6,
                            "age_under_19": 10,
                            "age_19_to_24": 40,
                            "age_25_plus": 110,
                            "total": 160
                        },
                        "description": "All",
                        "provider_id": 10000020,
                        "stats": {
                            "success_rate": 84.2
                        },
                        "national_stats": {
                            "success_rate": 68.9
                        },
                        "earnings": {},
                        "national_earnings": {},
                        "average_cost": 0
                    },
                    {
                        "subject_tier_2_code": 15.1,
                        "subject_tier_2_title": "Accounting and Finance",
                        "learner_stats": {},
                        "description": "Accounting and Finance",
                        "provider_id": 10000060,
                        "stats": {
                            "success_rate": 90.3
                        },
                        "national_stats": {
                            "success_rate": 76.1
                        },
                        "earnings": {
                            "median": 18700,
                            "proportion_above_21k": 0.33
                        },
                        "national_earnings": {
                            "median": 19100,
                            "proportion_above_21k": 0.34
                        },
                        "average_cost": 0
                    }
                ],
                "result_count": 2,
                "page_number": 1,
                "page_size": 50
            }