FORMAT: 1A
HOST: https://apprenticeship-scorecard-api.herokuapp.com/

# Apprenticeship Scorecard

API to access data on UK apprenticeships and providers

## Apprenticeships Collection [/apprenticeships?q=query-string&max_results=500&page_size=20&page_number=2]

List all (by default) apprenticeships in the data set. The results will be paged. The page size and page number
can be set by the relevant optional parameters and the total number of results that are selected can
be limited by the optional `max_results` parameter.

+ Parameters
    + query: learner_stats.total > 200 (string) - a query string that will be used to filter the list of apprenticeships
    + max_results: 500 (number) - limit the number of apprenticeships that are selected
    + page_size: 20 (number) - limit the number of apprenticeships that are returned in a page
    + page_number: 1 (number) - the page number to return

### List and filter apprenticeships [GET]


+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### List, filter and extract fields from apprenticeships [POST]



+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }